from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

from thorn.eval_review import build_result_review_context
from thorn.evidence import InferenceStatus
from thorn.latex import extract_project
from thorn.lean_export import LeanExport, LeanExportStatus, project_lean
from thorn.proof_obligations import ObligationStatus
from thorn.semantic_review_render import build_semantic_review_request
from thorn.semantic_transformations import (
    SemanticTransformation,
    SemanticTransformationIR,
    SemanticTransformationKind,
    build_semantic_transformation_ir,
)

_CASES = Path(__file__).parent / "lean_cases"


def _semantic(path: Path) -> SemanticTransformationIR:
    project = extract_project(path)
    unit = project.unit("thm:main")
    context = build_result_review_context(project, unit.identifier)
    request = build_semantic_review_request(context.items[0])
    return build_semantic_transformation_ir(
        unit,
        request,
        symbol_table=project.symbol_table,
        dependency_graph=project.dependency_graph,
    )


def _transfer_application(ir: SemanticTransformationIR) -> SemanticTransformation:
    for transformation in ir.transformations:
        if transformation.kind != SemanticTransformationKind.RESULT_APPLICATION:
            continue
        for address in transformation.support_atom_addresses:
            atom = ir.support_atom(address)
            if atom.referenced_result_identifier == "lem:transfer":
                return transformation
    raise AssertionError("missing recovered application of lem:transfer")


def _positive_export() -> tuple[SemanticTransformationIR, LeanExport]:
    semantic = _semantic(_CASES / "theorem_application.tex")
    return semantic, project_lean(semantic)


def test_positive_latex_reaches_complete_deterministic_lean() -> None:
    semantic, export = _positive_export()
    application = _transfer_application(semantic)
    application_obligation = semantic.obligation(application.obligation_addresses[0])

    assert application.status == InferenceStatus.CONFIDENT
    assert application_obligation.status == ObligationStatus.DISCHARGED
    assert export.status == LeanExportStatus.COMPLETE
    assert export.is_mechanically_checkable
    assert export.obligations == ()
    assert "sorry" not in export.source
    assert project_lean(semantic) == export
    assert export.source == (
        "-- Generated by Thorn from canonical Proof IR.\n"
        "-- Thorn Lean export status: complete\n"
        "theorem thorn_thm_main (P Q : Nat → Prop) (r1 : P 0) "
        "(r2 : ∀ x : Nat, P x → Q x) : Q 0 := by\n"
        "  have c1 : P 0 := r1\n"
        "  have c2 : Q 0 := r2 0 r1\n"
        "  exact c2\n"
    )


def test_positive_generated_source_is_accepted_by_pinned_lean(tmp_path: Path) -> None:
    _semantic_ir, export = _positive_export()
    lean = shutil.which("lean")
    if lean is None:
        if os.getenv("THORN_REQUIRE_LEAN") == "1":
            pytest.fail("Lean contract requires the pinned lean executable")
        pytest.skip("Lean is exercised by the dedicated pinned Lean contract workflow")

    generated = tmp_path / "thorn_handoff.lean"
    generated.write_text(export.source, encoding="utf-8")
    completed = subprocess.run(
        [lean, str(generated)],
        check=False,
        capture_output=True,
        text=True,
        env={**os.environ, "OPENAI_API_KEY": ""},
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr


def test_missing_premise_stays_partial_source_addressed_hole() -> None:
    semantic = _semantic(_CASES / "theorem_application_missing_premise.tex")
    application = _transfer_application(semantic)
    semantic_obligation = semantic.obligation(application.obligation_addresses[0])
    export = project_lean(semantic)

    assert semantic_obligation.status == ObligationStatus.UNRESOLVED
    assert application.status == InferenceStatus.UNRESOLVED
    assert export.status == LeanExportStatus.PARTIAL
    assert not export.is_mechanically_checkable
    assert len(export.obligations) == 1
    hole = export.obligations[0]
    assert hole.reason == "missing_result_precondition"
    assert hole.semantic_obligation_address == semantic_obligation.address
    assert hole.source_addresses == semantic_obligation.source_addresses
    assert hole.source_addresses
    assert "THORN_FORMALIZATION_OBLIGATION" in export.source
    assert "have thorn_obligation_lh1 : P 0 := by\n    sorry" in export.source
    assert "have c2 : Q 0 := r2 0 thorn_obligation_lh1" in export.source
    assert "Thorn Lean export status: partial" in export.source

    proof = semantic.higher.resolved.proof
    sources = [proof.source(address) for address in hole.source_addresses]
    assert any(source.referenced_result_identifier == "lem:transfer" for source in sources)
    assert all(source.ir_identifier for source in sources)


def test_unresolved_application_never_becomes_complete_on_repeat_export() -> None:
    semantic = _semantic(_CASES / "theorem_application_missing_premise.tex")
    first = project_lean(semantic)
    second = project_lean(semantic)

    assert first == second
    assert first.status == LeanExportStatus.PARTIAL
    assert not first.is_mechanically_checkable
    assert first.obligations
